### ISSUE TITLE
editing classes/objects

### ISSUE THREAD

**Issue by CharlesAE** [nathantannar4/Parse-Dashboard-for-iOS#1]
really like this project, was just wondering how do we edit classes and/or objects

**Comment by nathantannar4** [comment]
Thanks Charles! Editing some data types still is not supported, such as pointers, relations and arrays, but for other basic ones left swiping on an object cell should bring up the option to edit or delete the value. I did add support so that if an object does contain a pointer you can easily tap the cell to view the object it is pointing too.
