### ISSUE TITLE
Apple App Store Release

### ISSUE THREAD

**Issue by nathantannar4** [nathantannar4/Parse-Dashboard-for-iOS#8]
For anyone that is following this project, I want to re release this on the App Store but want to be able to have its sales cover the annual membership cost. What would be a fair price to ask?

**Comment by mrmarcsmith** [comment]
I can distribute it for you under my Apple account if that would help the project?

**Comment by mrmarcsmith** [comment]
I would love to see this project back in the App Store helping people again!

**Comment by mrmarcsmith** [comment]
Your project lives again! I just went nuts fixing swift/Obj C compile error, crashes because of outdated dependency code, etc but is finally works again.  I also ripped out the donation buttons since I'm not interested in making money that rightfully belongs to you off this project, I just want people to be able to use it again.  If you want to start maintaining this project/app let me know and I can pass the baton back to you, in the mean time I have submitted to the App Store. Hopefully this drums up some interest in the project!

**Comment by mrmarcsmith** [comment]
Hey @nathantannar4, Looking back I was quite excited to get this back into the App Store and flew right by the fact that you hadn't responded to my previous question about personal permission to distribute it or if you wanted to do it. I apologize for that, my eagerness got the better of me.  What would you like to do?
